version: '2'
services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
      DB_EXTENSION: pg_trgm
      DB_NAME: gitlabhq_production
      DB_PASS: xxxxxxx
      DB_USER: gitlab
    volumes:
    - /data/gitlab/postgresql:/var/lib/postgresql:Z
    labels:
      io.rancher.scheduler.affinity:host_label: git=1
  gitlab:
    image: sameersbn/gitlab:9.2.5
    environment:
      DB_ADAPTER: postgresql
      DB_HOST: postgresql
      DB_NAME: gitlabhq_production
      DB_PASS: xxxxxxx
      DB_PORT: '5432'
      DB_USER: gitlab
      DEBUG: 'false'
      GITLAB_BACKUP_EXPIRY: '259200'
      GITLAB_BACKUP_SCHEDULE: daily
      GITLAB_BACKUP_TIME: 01:00
      GITLAB_EMAIL: git@xxxxxxx.com
      GITLAB_EMAIL_REPLY_TO: noreply@xxxxxxx.com
      GITLAB_HOST: git.xxxxxxx.com
      GITLAB_HTTPS: 'false'
      GITLAB_INCOMING_EMAIL_ADDRESS: noreply@xxxxxxx.com
      GITLAB_NOTIFY_ON_BROKEN_BUILDS: 'true'
      GITLAB_NOTIFY_PUSHER: 'false'
      GITLAB_PORT: '80'
      GITLAB_RELATIVE_URL_ROOT: ''
      GITLAB_ROOT_EMAIL: root@xxxxxxx.com
      GITLAB_ROOT_PASSWORD: ''
      GITLAB_SECRETS_DB_KEY_BASE: long-and-random-alphanumeric-string
      GITLAB_SECRETS_OTP_KEY_BASE: long-and-random-alphanumeric-string
      GITLAB_SECRETS_SECRET_KEY_BASE: long-and-random-alphanumeric-string
      GITLAB_SSH_PORT: '10022'
      GITLAB_TIMEZONE: Beijing
      IMAP_ENABLED: 'false'
      IMAP_HOST: imap.exmail.qq.com
      IMAP_PASS: abc@xxxxxxx
      IMAP_PORT: '993'
      IMAP_SSL: 'true'
      IMAP_STARTTLS: 'false'
      IMAP_USER: git@xxxxxxx.com
      OAUTH_ENABLED: 'false'
      REDIS_HOST: redis
      REDIS_PORT: '6379'
      SMTP_AUTHENTICATION: login
      SMTP_DOMAIN: smtp.exmail.qq.com
      SMTP_ENABLED: 'true'
      SMTP_HOST: smtp.exmail.qq.com
      SMTP_PASS: Gitxxxxxx
      SMTP_PORT: '25'
      SMTP_STARTTLS: 'true'
      SMTP_USER: git@xxxxxxx.com
      SSL_SELF_SIGNED: 'false'
      TZ: Asia/Shanghai
      VIRTUAL_HOST: git.xxxxxxx.com
      RACK_ATTACK_ENABLED: 'false'
    volumes:
    - /data/gitlab/git:/home/git/data:Z
    labels:
      io.rancher.scheduler.affinity:host_label: git=1
  redis:
    image: sameersbn/redis:latest
    volumes:
    - /data/gitlab/redis:/var/lib/redis:Z
    command:
    - --loglevel warning
    labels:
      io.rancher.scheduler.affinity:host_label: git=1
